import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

interface Props {
  data: Results[];
}

interface Results {
  name: {
    common: string;
  };
  population: number;
  area: number;
}

export default function Home({ data }: Props) {
  const [text, setText] = useState("");

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="px-5 md:px-7">
        <p className="mb-6 font-semibold">Found {data.length} Countries</p>
        <form>
          <input
            className="pl-2 h-12 w-full md:w-2/4 rounded-md outline-none text-black"
            type="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Filter by Name"
          />
        </form>

        <div className="mt-5">
          <div className="flex justify-between mb-4 px-2">
            <p>Name</p>
            <p>Population</p>
            <p className="hidden md:block">Area</p>
          </div>
          {data
            .filter((res) => {
              if (text === "") {
                return res;
              } else if (
                res.name.common.toLowerCase().includes(text.toLowerCase())
              ) {
                return res;
              }
            })
            .map((res, id) => (
              <Link
                href={"/country/" + res.name.common}
                className="grid grid-cols-2 md:grid-cols-3 content-center mb-4 rounded-md px-2 py-4 bg-[#243a2f]"
                key={id}
              >
                <p>{res.name.common}</p>
                <p className="justify-self-end md:justify-self-center">
                  {res.population}
                </p>
                <p className="hidden justify-self-end md:block">{res.area}</p>
              </Link>
            ))}
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await res.json();
  return {
    props: { data }, // will be passed to the page component as props
  };
}
